// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Yunus Emre Alpu",
            "url": "https://yunusemrealpu.netlify.app",
            "email": "YunusAlpu@icloud.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/league": {
            "get": {
                "description": "Get the current state of the league including all teams and matches",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "league"
                ],
                "summary": "Get league",
                "responses": {
                    "200": {
                        "description": "Current league state",
                        "schema": {
                            "$ref": "#/definitions/models.League"
                        }
                    }
                }
            }
        },
        "/api/league/initialize": {
            "post": {
                "description": "Initialize a new league with the provided teams",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "league"
                ],
                "summary": "Initialize league",
                "parameters": [
                    {
                        "description": "Teams to initialize",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.InitializeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "League initialized successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/league/match/{id}": {
            "put": {
                "description": "Update the result of a specific match",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "league"
                ],
                "summary": "Update match",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Match ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New match scores",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UpdateMatchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Match updated successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request or match not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/league/play-all-weeks": {
            "post": {
                "description": "Simulate all remaining weeks of matches in the league",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "league"
                ],
                "summary": "Play all weeks",
                "responses": {
                    "200": {
                        "description": "All weeks played successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "League not initialized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/league/play-next-week": {
            "post": {
                "description": "Simulate the next week of matches in the league",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "league"
                ],
                "summary": "Play next week",
                "responses": {
                    "200": {
                        "description": "Week played successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "All weeks already played or league not initialized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/league/predictions": {
            "get": {
                "description": "Get championship predictions using Monte Carlo simulation",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "league"
                ],
                "summary": "Get predictions",
                "responses": {
                    "200": {
                        "description": "Championship predictions",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Prediction"
                            }
                        }
                    }
                }
            }
        },
        "/api/league/reset": {
            "post": {
                "description": "Reset the league to its initial state",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "league"
                ],
                "summary": "Reset league",
                "responses": {
                    "200": {
                        "description": "League reset successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "League not initialized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/league/standings": {
            "get": {
                "description": "Get the current league standings sorted by points",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "league"
                ],
                "summary": "Get standings",
                "responses": {
                    "200": {
                        "description": "League standings",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.InitializeRequest": {
            "type": "object",
            "required": [
                "teams"
            ],
            "properties": {
                "teams": {
                    "type": "array",
                    "minItems": 2,
                    "items": {
                        "type": "object",
                        "required": [
                            "name",
                            "power"
                        ],
                        "properties": {
                            "logo": {
                                "type": "string"
                            },
                            "name": {
                                "type": "string"
                            },
                            "power": {
                                "type": "integer",
                                "maximum": 100,
                                "minimum": 1
                            }
                        }
                    }
                }
            }
        },
        "handlers.UpdateMatchRequest": {
            "type": "object",
            "properties": {
                "awayScore": {
                    "type": "integer",
                    "minimum": 0
                },
                "homeScore": {
                    "type": "integer",
                    "minimum": 0
                }
            }
        },
        "models.League": {
            "type": "object",
            "properties": {
                "currentWeek": {
                    "type": "integer"
                },
                "fixtures": {
                    "description": "Fixtures grouped by week",
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/models.Match"
                        }
                    }
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "predictions": {
                    "description": "Team ID -\u003e Win probability",
                    "type": "object",
                    "additionalProperties": {
                        "type": "number"
                    }
                },
                "teams": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/models.Team"
                    }
                },
                "totalWeeks": {
                    "type": "integer"
                }
            }
        },
        "models.Match": {
            "type": "object",
            "properties": {
                "awayScore": {
                    "type": "integer"
                },
                "awayTeamId": {
                    "type": "string"
                },
                "awayTeamName": {
                    "type": "string"
                },
                "homeScore": {
                    "type": "integer"
                },
                "homeTeamId": {
                    "type": "string"
                },
                "homeTeamName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/models.MatchStatus"
                },
                "week": {
                    "type": "integer"
                }
            }
        },
        "models.MatchStatus": {
            "type": "string",
            "enum": [
                "not_played",
                "played"
            ],
            "x-enum-varnames": [
                "StatusNotPlayed",
                "StatusPlayed"
            ]
        },
        "models.Prediction": {
            "type": "object",
            "properties": {
                "probability": {
                    "description": "Percentage (0-100)",
                    "type": "number"
                },
                "teamId": {
                    "type": "string"
                },
                "teamName": {
                    "type": "string"
                }
            }
        },
        "models.Team": {
            "type": "object",
            "properties": {
                "drawn": {
                    "description": "Matches drawn",
                    "type": "integer"
                },
                "goalsAgainst": {
                    "description": "Goals conceded",
                    "type": "integer"
                },
                "goalsFor": {
                    "description": "Goals scored",
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "logo": {
                    "description": "Team logo URL",
                    "type": "string"
                },
                "lost": {
                    "description": "Matches lost",
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "played": {
                    "description": "Matches played",
                    "type": "integer"
                },
                "points": {
                    "description": "Total points",
                    "type": "integer"
                },
                "power": {
                    "description": "Team strength (0-100)",
                    "type": "integer"
                },
                "won": {
                    "description": "Matches won",
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{"http", "https"},
	Title:            "Stadia",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
